### ISSUE TITLE
按照步骤来，到破解那一步显示不是有效的授权码 ，是怎么回事？

### ISSUE THREAD

**Issue by hhszzheng** [aladdinding/Confluence-and-Jira#1]

**Comment by munding** [comment]
版本是一样的吗？后续的版本我没有测试过。还有你的激活命令行可以发出来看看么

**Comment by hhszzheng** [comment]
是这样 我在本地run 可以激活  换成公司的paas平台就激活不了 地址就是换了下ip 服务器id 还有 conf  jira 那个参数


在2020年07月21日 22:15，Aladdin 写道：

版本是一样的吗？后续的版本我没有测试过。还有你的激活命令行可以发出来看看么

**Comment by munding** [comment]
这个流程在我们内部线上服务器上部署也是通过的，并没有遇到 不是有效授权码这样的情况。这个是破解工具的项目地址 https://gitee.com/pengzhile/atlassian-agent 你看看是不是有什么参数漏掉了

**Comment by hhszzheng** [comment]
有可能是填的问题 我明天再试试吧 步骤我是按照你这里面来的  我现在尝试的版本是conf 6.13 jira7.12 本地run都通过了 就是很奇怪部署到paas上就失效了

在2020年07月21日 22:29，Aladdin 写道：

这个流程在我们内部线上服务器上部署也是通过的，并没有遇到 不是有效授权码这样的情况。这个是破解工具的项目地址 https://gitee.com/pengzhile/atlassian-agent 你看看是不是有什么参数漏掉了

**Comment by chaos-lsc** [comment]
我也出现了这个问题，confluence版本7.13.5-ubuntu，在 catalina.out 里面已经看到了 ========= agent working ========= 字样，而且使用 `ps -ef |grep java|grep agent` 命令，能看到 -javaagent 相关字样，说明破解已经完成。
使用命令`java -jar atlassian-agent.jar -d -m test@test.com -n BAT -p 'conf' -o http://{url}:8090 -s B1XV-4BND-1UB5-85DR`获取密钥，复制粘贴之后得到提示：That's not a valid license key.
请问我还有什么地方需要看看

**Comment by munding** [comment]
降版本试试 如7.9.3

**Comment by chaos-lsc** [comment]
> 

需要新版本，在服务器上使用比 7.13.5 低的版本，会被黑客攻击，难受

**Comment by chaos-lsc** [comment]
> 

更奇怪的是，只是在容器里面使用 start 或 stop confluence.sh ，还能通过域名进入 confluence 输入 licences ，一旦重启容器，就不能正常进入输入 license 界面了，报错：`BootstrapException: Unable to bootstrap application: failed to find config at: /var/atlassian/application-data/confluence/confluence.cfg.xml`
