### ISSUE TITLE
请问这种方式可以破解其他插件吗？？我试了下好像没效果啊

### ISSUE THREAD

**Issue by jwh5566** [aladdinding/Confluence-and-Jira#2]
confluence 7.4.7
试了一些表单插件，提示都是：
您的应用许可证无效。确保整个应用许可证（包括换行符）与提供的完全一致。

**Comment by munding** [comment]
需要confluence有整个破解环境吧 而不是单独生成一个激活码

**Comment by jwh5566** [comment]
嗯 &nbsp;已经测试成功了，确实是需要整个破解环境的 &nbsp;谢谢大佬！





------------------ 原始邮件 ------------------
发件人: 阿拉丁 ***@***.***&gt;
发送时间: 2021年8月12日 10:09
收件人: aladdinding/Confluence-and-Jira ***@***.***&gt;
抄送: 蒋文华 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[aladdinding/Confluence-and-Jira] 请问这种方式可以破解其他插件吗？？我试了下好像没效果啊 (#2)





 
需要confluence有整个破解环境吧 而不是单独生成一个激活码
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by munding** [comment]
原atlassian-agent项目作者关闭了，这是我fork的地址：https://gitee.com/aladdinding/atlassian-agent
